server:
  port: 3000

# spring
spring:
  data:
    mongodb:
      host: localhost
      database: login
      username: minseokgo
      password: 111122
      uri: mongodb://localhost:27017/login

jwt:
  issuer: rhalstjr1999@naver.com
  secretKey: rhalstjrrhalstjrrhalstjrrhalstjr
  tokenPrefix: Bearer
